apiVersion: apps/v1
kind: Deployment
metadata: { name: react-frontend }
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
        - name: react-frontend
          image: alperen941/my-react-app:prod   # ← push after building
          ports: [ { containerPort: 80 } ]
---
apiVersion: v1
kind: Service
metadata: { name: frontend-service }
spec:
  selector: { app: frontend }
  type: NodePort
  ports:
    - port: 80          # inside cluster
      targetPort: 80    # container
      nodePort: 30007   # ⇐ browser will hit this
