name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  REGISTRY: docker.io
  IMAGE_NS: alperen941          # ← dit Docker Hub-brugernavn
  TAG_LATEST: latest
  TAG_SHA: ${{ github.sha }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- BACKEND ----------
      - name: Set up JDK 21 + Maven-cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run backend unit tests
        working-directory: java-backend
        run: mvn -B test

      - name: Build backend JAR (skip tests)
        working-directory: java-backend
        run: mvn -B clean package -DskipTests spring-boot:repackage

      # ---------- FRONTEND ----------
      - name: Set up Node 20 + npm-cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: react-frontend/package-lock.json

      - name: Build frontend
        working-directory: react-frontend
        run: |
          npm ci
          npm run build          # dist/

      # ---------- LOGIN ----------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- BUILD + PUSH IMAGES ----------
      - name: Build & push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./java-backend
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NS }}/java-backend:${{ env.TAG_LATEST }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NS }}/java-backend:${{ env.TAG_SHA }}
          push: true

      - name: Build & push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./react-frontend
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NS }}/react-frontend:${{ env.TAG_LATEST }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NS }}/react-frontend:${{ env.TAG_SHA }}
          push: true
